Sprint 2
zizi-shoot/middle.messenger.praktikum.yandex pull request #6
Opened 2022-11-21 22:41 UTC by zizi-shoot

Привет!

Есть две проблемы, которые вообще не знаю как победить. Буду благодарен, если подскажешь в каком направлении двигаться:

1. Если инпут невалиден, то при фокусе на нём происходит "очищение" ошибок, вследствие чего идёт ререндер и потеря фокуса. То есть чтобы начать печатать в инпуте, надо ещё раз в него тыкнуть.

2. В хроме при фокусе после события blur/focusout  вылетает ошибка в консоль, после чего события фокуса перестают нормально отрабатывать. Проверял ещё в Safari и Firefox, там всё норм отрабатывает. Более подробно описано в ишью - https://github.com/zizi-shoot/middle.messenger.praktikum.yandex/issues/2

2022-11-22 20:19 UTC, podlovchenko requested changes
Привет, посмотрела в чем дело
В toggleErrors src/components/Form/Form.ts сейчас устанавливается hasError в зависимости от isFocusIn, но нужно валидировать и устанавливать hasError в зависимости от наличия ошибок
То есть очищение ошибок должно происходить только в случае, если handleValidateForm вернет valid=true
Перед следующей сдачей перепроверь валидацию по заданию, пожалуйста, там есть несколько ошибок в регулярках, например такое dfgfdgf#$#$ проходит для имени, хотя не должно

В остальном все здорово 👍

2022-11-22 20:19 UTC, podlovchenko commented on src/components/FormField/form-field.module.css
> +.containerError input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-11-22 20:19 UTC, podlovchenko commented on src/core/HTTPTransport.ts
> +  method: keyof typeof HTTPTransport.METHOD
Можно определить enum Method

2022-11-23 10:49 UTC, zizi-shoot commented on src/components/FormField/form-field.module.css
> +.containerError input {
Поправил

2022-11-23 10:49 UTC, zizi-shoot commented on src/core/HTTPTransport.ts
> +  method: keyof typeof HTTPTransport.METHOD
Можно, но я как-то намеренно не использую всякие доп штуки из TS а-ля enums, namespace и всякое такое, что компилируется в реальный лишний код на JS

Выглядит сие страшненько😁
<img width="661" alt="Screenshot 2022-11-23 at 13 48 31" src="https://user-images.githubusercontent.com/59991930/203528100-3d5bd399-eef5-4cd5-bb11-bde49f65a56c.png">

2022-11-23 10:57 UTC, zizi-shoot commented
1. Регулярку для имени сделал изначально, но забыл подставить. Сейчас поправил.

2. Немного подкрутил регулярку для телефона, но с телефоном там вообще много мороки. Лучше всё-таки маски сначала задать, чтобы избежать зоопарка вводимых данных, а там уже доставать значения и валидировать. Не знаю насколько сейчас целесообразно упарываться в такое развитие дел.

3. В других валидациях ошибок не нашёл.

4. Поменял поведение метода toggleErrors, в связи с этим убрал вообще обработку события focus. Нужно ли вообще как-то отдельно focus обрабатывать? Не смог придумать подходящего поведения ¯\_(ツ)_/¯

2022-11-23 18:46 UTC, podlovchenko reviewed
Спасибо за оперативные правки, работу принимаю)

2022-11-23 20:22 UTC, merged